### ISSUE TITLE
Reset the data

### ISSUE THREAD

**Issue by Deleora** [utkarsh914/whatsapp-stalker#4]
Hey,
I'm using the script in bookmark and it's working perfectly. Now I would like to reset the `csvContent` after I download the `csv` file so that the next time I download the `csv` it does not contain the already downloaded log. 
I've tried putting `k="data:text/csv;charset=utf-8,Name,From,To,Duration\n";` (basically trying to reset the content string) in the last line of `function c(a){...}` but it's not working. So I would really appreciate a little help here. Thanks in advance 😄

**Comment by utkarsh914** [comment]
Hi @Deleora, I've updated it  and added the reset function.
To reset csv content, we just set the variable `csvContent = "data:text/csv;charset=utf-8,Name,From,To,Duration\n";`
So, just a button needed to be added in function `putCSVLink`  which calls another function to reset the value of above variable.
Have a look at the updated code in the repo :)

**Comment by Deleora** [comment]
Wow, it's working great. Thanks a lot!! 😄
