### ISSUE TITLE
Not working? 

### ISSUE THREAD

**Issue by dineshkumarb** [utkarsh914/whatsapp-stalker#6]
Not working as WhatsApp web has new CSS?

**Comment by utkarsh914** [comment]
Hello @dineshkumarb ! Yes, WhatsApp's code keeps changing a bit from time to time, and we need to keep the script in sync with it. Thanks for reminding. I've updated the source code.

**Comment by dineshkumarb** [comment]
Thank you Utkarsh! Now I understood your CSS document selector much useful and I love this snippet! keep going, can you also write it for Botim, if you think its relatively easy?
