### ISSUE TITLE
not working since 26/02/2021

### ISSUE THREAD

**Issue by callofthesea** [utkarsh914/whatsapp-stalker#7]
Not working since 26-02-2021. it Worked fine up to then I was using the code having set it as a bookmark in Chrome when I wanted to turn it on on whatsapp desktop, Tried the extension too and it is not working. I also notice another coder had the same issue that occurred on the same date with this. Looks like whatsapp changed some of their code. Hopefully this will be fixed here soon.

**Comment by utkarsh914** [comment]
Hello @callofthesea ! Yes, WhatsApp's code keeps changing time to time, and we need to keep the extension and script in sync with it. Thanks for reminding. I've updated the source code.

**Comment by callofthesea** [comment]
Thank you! Excellent Script!
