### ISSUE TITLE
Convert JS code to bookmark format

### ISSUE THREAD

**Issue by Deleora** [utkarsh914/whatsapp-stalker#8]
Hi mate,
I find the bookmark method very handy but I make some modifications in your script according to my needs and I'm having trouble converting the JS code to bookmark format.  Can you please share with me how you make that bookmark string from your code?
And I appreciate the quick fix of the script too, Thanks!
Cheers!!

**Comment by utkarsh914** [comment]
Hi @Deleora,
I use [https://chriszarate.github.io/bookmarkleter/](url). You may give it a try!
And, welcome :)
